apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-nginx.labels" . | nindent 4 }}
    environment: {{ .Values.environment }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-nginx.selectorLabels" . | nindent 8 }}
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        - name: TEAM
          value: {{ .Values.config.team }}
        - name: OWNER
          value: {{ .Values.config.owner }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
